form:
  title: CustomNamesForGeyserMC
  enterNick: Enter your nick
  example: ElPrimo
  wrongTitle: Error
  wrongNick: Please use normal nick

reconnect: Please reconnect to server again

useMetric: true

checkUpdates: true
version:
  new: pls download new plugin version https://github.com/Mirik9724/CustomNamesForGeyserMC/releases
  noFound: You use a latest version
  er: We can't check for updates


checkValidNick: true
#use 1-3, default is 3
minLength: 3
# If m.L. is â‰¥ 16, Minecraft correctly handles such nicknames; otherwise, it does not."
maxLength: 16

# Currently has no effect
# Will be deleted
useTempNicks: false